// enum ProjectEventType {
//   CREATED
//   UPDATED
//   DELETED
//   RESTORED

//   STATUS_CHANGED

//   MEMBER_ADDED
//   MEMBER_REMOVED
//   MEMBER_ROLE_CHANGED

//   PRIORITY_CHANGED
//   DUE_DATE_CHANGED
//   START_DATE_CHANGED
//   NAME_CHANGED
//   DESCRIPTION_CHANGED

//   COMMENT_ADDED
// }

export const ProjectEventType = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  RESTORED: 'RESTORED',

  STATUS_CHANGED: 'STATUS_CHANGED',

  MEMBER_ADDED: 'MEMBER_ADDED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',

  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  DUE_DATE_CHANGED: 'DUE_DATE_CHANGED',
  START_DATE_CHANGED: 'START_DATE_CHANGED',
  NAME_CHANGED: 'NAME_CHANGED',
  DESCRIPTION_CHANGED: 'DESCRIPTION_CHANGED',

  COMMENT_ADDED: 'COMMENT_ADDED',
} as const;

export type ProjectEventType =
  (typeof ProjectEventType)[keyof typeof ProjectEventType];

// enum TaskActivityEntity {
//   TASK
//   COMMENT
//   ASSIGNEE
//   ATTACHMENT
//   CHECKLIST
//   LABEL
//   TIME_ENTRY
// }

export const TaskActivityEntity = {
  TASK: 'TASK',
  COMMENT: 'COMMENT',
  ASSIGNEE: 'ASSIGNEE',
  ATTACHMENT: 'ATTACHMENT',
  CHECKLIST: 'CHECKLIST',
  LABEL: 'LABEL',
  TIME_ENTRY: 'TIME_ENTRY',
} as const;

export type TaskActivityEntity =
  (typeof TaskActivityEntity)[keyof typeof TaskActivityEntity];

// enum TaskEventType {
//   CREATED
//   UPDATED
//   DELETED
//   RESTORED
//   ARCHIVED

//   STATUS_CHANGED

//   ASSIGNEE_ADDED
//   ASSIGNEE_REMOVED

//   COMMENT_ADDED
//   COMMENT_EDITED
//   COMMENT_DELETED

//   ATTACHMENT_ADDED
//   ATTACHMENT_REMOVED

//   CHECKLIST_ITEM_ADDED
//   CHECKLIST_ITEM_UPDATED
//   CHECKLIST_ITEM_REMOVED

//   LABEL_ADDED
//   LABEL_REMOVED

//   DUE_DATE_CHANGED
//   START_DATE_CHANGED

//   PRIORITY_CHANGED

//   ESTIMATE_CHANGED

//   TIME_LOGGED

//   CUSTOM
// }

export const TaskEventType = {
  CREATED: 'CREATED',
  UPDATED: 'UPDATED',
  DELETED: 'DELETED',
  RESTORED: 'RESTORED',
  ARCHIVED: 'ARCHIVED',

  STATUS_CHANGED: 'STATUS_CHANGED',

  ASSIGNEE_ADDED: 'ASSIGNEE_ADDED',
  ASSIGNEE_REMOVED: 'ASSIGNEE_REMOVED',

  COMMENT_ADDED: 'COMMENT_ADDED',
  COMMENT_EDITED: 'COMMENT_EDITED',
  COMMENT_DELETED: 'COMMENT_DELETED',

  ATTACHMENT_ADDED: 'ATTACHMENT_ADDED',
  ATTACHMENT_REMOVED: 'ATTACHMENT_REMOVED',

  CHECKLIST_ITEM_ADDED: 'CHECKLIST_ITEM_ADDED',
  CHECKLIST_ITEM_UPDATED: 'CHECKLIST_ITEM_UPDATED',
  CHECKLIST_ITEM_REMOVED: 'CHECKLIST_ITEM_REMOVED',

  LABEL_ADDED: 'LABEL_ADDED',
  LABEL_REMOVED: 'LABEL_REMOVED',

  DUE_DATE_CHANGED: 'DUE_DATE_CHANGED',
  START_DATE_CHANGED: 'START_DATE_CHANGED',

  PRIORITY_CHANGED: 'PRIORITY_CHANGED',

  ESTIMATE_CHANGED: 'ESTIMATE_CHANGED',

  TIME_LOGGED: 'TIME_LOGGED',

  CUSTOM: 'CUSTOM',
} as const;

export type TaskEventType = (typeof TaskEventType)[keyof typeof TaskEventType];
